In [7]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('organisation.csv')

In [9]:
df.head(10)
#to get first 10 rows default is 5

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
5,cC757116fe1C085,Henry-Thompson,http://morse.net/,Bahamas,Face-to-face well-modulated customer loyalty,1992,Primary / Secondary Education,4914
6,219233e8aFF1BC3,Hansen-Everett,https://www.kidd.org/,Pakistan,Seamless disintermediate collaboration,2018,Publishing Industry,7832
7,ccc93DCF81a31CD,Mcintosh-Mora,https://www.brooks.com/,Heard Island and McDonald Islands,Centralized attitude-oriented capability,1970,Import / Export,4389
8,0B4F93aA06ED03e,Carr Inc,http://ross.com/,Kuwait,Distributed impactful customer loyalty,1996,Plastics,8167
9,738b5aDe6B1C6A5,Gaines Inc,http://sandoval-hooper.com/,Uzbekistan,Multi-lateral scalable protocol,1997,Outsourcing / Offshoring,9698

In [11]:
df.tail(12)
#to get bottom 12 rows default is 5

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
94,4e91eD25f486110,"Best, Wade and Shepard",https://zimmerman.com/,Zimbabwe,Innovative background definition,1991,Gambling / Casinos,4873
95,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785
100,4e91eD25f486110,"Best, Wade and Shepard",https://zimmerman.com/,Zimbabwe,Innovative background definition,1991,Gambling / Casinos,4873
101,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
102,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
103,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
104,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
105,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [12]:
df.columns
# to see all columns present

Index(['Organization Id', 'Name', 'Website', 'Country', 'Description',
       'Founded', 'Industry', 'Number of employees'],
      dtype='object')

In [13]:
df.dtypes
# to get the data types of all columns

Organization Id        object
Name                   object
Website                object
Country                object
Description            object
Founded                 int64
Industry               object
Number of employees     int64
dtype: object

In [14]:
df.describe()
# to describe the math stats for numerical columns

           Founded  Number of employees
count   106.000000           106.000000
mean   1995.009434          4830.179245
std      15.664637          2854.523020
min    1970.000000           236.000000
25%    1982.500000          2653.750000
50%    1993.000000          4873.000000
75%    2009.000000          7481.250000
max    2021.000000          9995.000000

In [15]:
df.describe(include="object")
# to describe math stats for string and object columns

,Organization Id,Name,Website,Country,Description,Industry
count,106,106,106,106,106,106
unique,100,100,100,84,100,72
top,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Sweden,Synergistic background access,Plastics
freq,2,2,2,3,2,4

In [16]:
df.Website

0                  https://price.net/
1      http://www.hall-buchanan.info/
2           http://sullivan-reed.com/
3                 https://becker.com/
4              http://www.brewer.com/
                    ...
101             https://mcdowell.org/
102                 http://duffy.com/
103           http://www.flowers.net/
104            https://www.burke.net/
105           http://www.herring.com/
Name: Website, Length: 106, dtype: object

In [17]:
df['Organization Id']

0      FAB0d41d5b5d22c
1      6A7EdDEA9FaDC52
2      0bFED1ADAE4bcC1
3      2bFC1Be8a4ce42f
4      9eE8A6a4Eb96C24
            ...
101    0a0bfFbBbB8eC7c
102    BA6Cd9Dae2Efd62
103    E7df80C60Abd7f9
104    AFc285dbE2fEd24
105    e9eB5A60Cef8354
Name: Organization Id, Length: 106, dtype: object

In [18]:
df[['Name','Website']]

                        Name                         Website
0                Ferrell LLC              https://price.net/
1    Mckinney, Riley and Day  http://www.hall-buchanan.info/
2                 Hester Ltd       http://sullivan-reed.com/
3             Holder-Sellers             https://becker.com/
4                Mayer Group          http://www.brewer.com/
..                       ...                             ...
101             Holmes Group           https://mcdowell.org/
102                 Good Ltd               http://duffy.com/
103        Clements-Espinoza         http://www.flowers.net/
104               Mendez Inc          https://www.burke.net/
105           Watkins-Kaiser         http://www.herring.com/

[106 rows x 2 columns]

In [20]:
df.Country.unique()

array(['Papua New Guinea', 'Finland', 'China', 'Turkmenistan',
       'Mauritius', 'Bahamas', 'Pakistan',
       'Heard Island and McDonald Islands', 'Kuwait', 'Uzbekistan',
       'Bouvet Island (Bouvetoya)', 'Denmark', 'Liberia',
       'United Arab Emirates', 'Sweden', 'Honduras', 'Uganda',
       'Hong Kong', 'Botswana', 'Korea', 'Luxembourg', 'Guadeloupe',
       'Monaco', 'Belgium', 'South Africa', 'Romania', 'Czech Republic',
       'Christmas Island', 'Philippines', 'Australia', 'Chad', 'Zimbabwe',
       'Nepal', 'Taiwan', 'Kyrgyz Republic', 'Bolivia', 'Kenya',
       'Guatemala', 'Belarus', 'Jersey', 'Grenada', 'Cape Verde',
       'Trinidad and Tobago', 'Benin', 'Western Sahara',
       'Northern Mariana Islands', 'Germany', 'Canada', 'Tonga',
       'French Southern Territories', "Cote d'Ivoire", 'Mayotte',
       'Cayman Islands', 'Nigeria', 'Marshall Islands', 'Palau', 'Turkey',
       'Timor-Leste', 'Vietnam', 'Reunion', 'Brazil', 'Eritrea',
       'United States Virgin Islands', 'Falkland Islands (Malvinas)',
       'Netherlands Antilles', 'Guernsey', 'Uruguay', 'Suriname',
       'Mongolia', 'Svalbard & Jan Mayen Islands', 'Togo', 'Latvia',
       'Cuba', 'Liechtenstein', 'Djibouti', 'Micronesia', 'Cameroon',
       'Cocos (Keeling) Islands', 'Mali', 'Burundi', 'Gibraltar',
       'El Salvador', 'Ethiopia', 'Anguilla'], dtype=object)

In [21]:
df.head()

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870

In [25]:
df[df['Country']=='United States Virgin Islands']

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
65,fdFbecbadcdCdf1,"Wilkinson, Charles and Arroyo",http://hunter-mcfarland.com/,United States Virgin Islands,Assimilated 24/7 archive,1996,Building Materials,602
87,8cC1bDa330a5871,Pineda-Morton,https://www.carr.com/,United States Virgin Islands,Grass-roots methodical info-mediaries,1991,Printing,6168

In [26]:
df[df.Founded==1996]

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
8,0B4F93aA06ED03e,Carr Inc,http://ross.com/,Kuwait,Distributed impactful customer loyalty,1996,Plastics,8167
65,fdFbecbadcdCdf1,"Wilkinson, Charles and Arroyo",http://hunter-mcfarland.com/,United States Virgin Islands,Assimilated 24/7 archive,1996,Building Materials,602
91,4e0719FBE38e0aB,Miles-Dominguez,http://www.turner.com/,Gibraltar,Organized empowering forecast,1996,Civic / Social Organization,897

In [29]:
df[(df.Country=='United States Virgin Islands') & (df.Founded==1996)]

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
65,fdFbecbadcdCdf1,"Wilkinson, Charles and Arroyo",http://hunter-mcfarland.com/,United States Virgin Islands,Assimilated 24/7 archive,1996,Building Materials,602

In [31]:
df.iloc[0]
# to get data based on row index

Organization Id                            FAB0d41d5b5d22c
Name                                           Ferrell LLC
Website                                 https://price.net/
Country                                   Papua New Guinea
Description            Horizontal empowering knowledgebase
Founded                                               1990
Industry                                          Plastics
Number of employees                                   3498
Name: 0, dtype: object

In [32]:
df.iloc[-1]

Organization Id                      e9eB5A60Cef8354
Name                                  Watkins-Kaiser
Website                      http://www.herring.com/
Country                                         Togo
Description            Synergistic background access
Founded                                         2009
Industry                          Financial Services
Number of employees                             2785
Name: 105, dtype: object

In [34]:
df.iloc[45:50]

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
45,1eD64cFe986BBbE,Walton-Barnett,https://ashley-schaefer.com/,Western Sahara,Right-sized clear-thinking flexibility,2001,Luxury Goods / Jewelry,1746
46,CbBbFcdd0eaE2cF,Bartlett-Arroyo,https://cruz.com/,Northern Mariana Islands,Realigned didactic function,1976,Civic / Social Organization,3987
47,49aECbDaE6aBD53,"Wallace, Madden and Morris",http://www.blevins-fernandez.biz/,Germany,Persistent real-time customer loyalty,2016,Pharmaceuticals,9443
48,7b3fe6e7E72bFa4,Berg-Sparks,https://cisneros-love.com/,Canada,Stand-alone static implementation,1974,Arts / Crafts,2073
49,c6DedA82A8aef7E,Gonzales Ltd,http://bird.com/,Tonga,Managed human-resource policy,1988,Consumer Goods,9069

In [37]:
cdf=df.copy()
cdf.set_index('Organization Id')

,Name,Website,Country,Description,Founded,Industry,Number of employees
Organization Id,,,,,,,
FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
...,...,...,...,...,...,...,...
0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [56]:
# cdf.loc(['AFc285dbE2fEd24'],axis=0)

TypeError: _LocationIndexer.__call__() got multiple values for argument 'axis'

In [58]:
# dropping columns 
# cdf.drop(columns=['Website','Country'])

# dropping rows based on index 
# cdf.drop([0,2])

# drop columns based on axis 
# cdf.drop([],axis=1)

# cdf.drop(labels=[])

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
5,cC757116fe1C085,Henry-Thompson,http://morse.net/,Bahamas,Face-to-face well-modulated customer loyalty,1992,Primary / Secondary Education,4914
6,219233e8aFF1BC3,Hansen-Everett,https://www.kidd.org/,Pakistan,Seamless disintermediate collaboration,2018,Publishing Industry,7832
...,...,...,...,...,...,...,...,...
101,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
102,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
103,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
104,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
105,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [61]:
df['mhund']=100
df

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees,mhund
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498,100
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952,100
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287,100
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921,100
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870,100
...,...,...,...,...,...,...,...,...,...
101,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988,100
102,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292,100
103,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236,100
104,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339,100
105,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785,100

In [64]:
df.iloc[1,5]=2018
df.head()

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees,mhund
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,2018,3498,100
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2018,Glass / Ceramics / Concrete,4952,100
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287,100
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921,100
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870,100

In [66]:
df['slaray']=df['Number of employees'] * 5000 * 12
df

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees,mhund,slaray
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,2018,3498,100,209880000
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2018,Glass / Ceramics / Concrete,4952,100,297120000
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287,100,317220000
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921,100,55260000
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870,100,472200000
...,...,...,...,...,...,...,...,...,...,...
101,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988,100,179280000
102,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292,100,257520000
103,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236,100,14160000
104,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339,100,20340000
105,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785,100,167100000

In [70]:
def doSomething(x):
    if(x>3000):
        return True
    
    return False

df['taxp']=df['Number of employees'].apply(doSomething)
df

,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees,mhund,slaray,taxp
0,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,2018,3498,100,209880000,True
1,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2018,Glass / Ceramics / Concrete,4952,100,297120000,True
2,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287,100,317220000,True
3,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921,100,55260000,False
4,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870,100,472200000,True
...,...,...,...,...,...,...,...,...,...,...,...
101,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988,100,179280000,False
102,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292,100,257520000,True
103,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236,100,14160000,False
104,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339,100,20340000,False
105,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785,100,167100000,False

In [71]:
df.to_csv('newdata.csv')

In [73]:
df.to_json('data.json')

In [74]:
df.to_html('data.html')

In [76]:
df.to_clipboard()

In [80]:
cricket={"players":["Steyn","Anderson","Malinga"],"Wickets":[439,345,567]}
dfd=pd.DataFrame.from_dict(cricket)
dfd

    players  Wickets
0     Steyn      439
1  Anderson      345
2   Malinga      567

In [10]:
ls=np.array([23,45,67,88])

dc={"name":"Saurabh","age":26}

ps=pd.Series(dc)

ps

name    Saurabh
age          26
dtype: object